---
layout: cv
title: Jacob Walker's CV
---
# Jacob Walker
Student And Data Operations
<div id="webaddress">

*[LinkedIn](https://www.linkedin.com/in/jacob-walker-a4a69130b/)*

---

## Education:

**Brigham Young University – Idaho – Rexburg, ID, Jan. 2024 – Present**  
*Bachelor of Science in Financial Economics | GPA 3.93*  
Expected Graduation Date: July 2027

**Chemeketa Community College – Salem, OR, Sept. 2019 – April 2021**

---

## Experience:

**Bank of Commerce: Data Operator/Fraud Specialist - January 2024–Present**

- Maximized efficiency of the end-of-day bank operations by creating a list of all end-of-day operations, saving the bank more than 30 minutes each night.

- Collaborated with management to provide organizational oversight and guidance by creating a one-page guide and checklist, increasing proficiency in fraud detection between coworkers.

- Analyzed the data of over 500 checks per day while ensuring key bank processes are completed at the indicated times.

**Solitude Landscaping: Crew Lead/Translator - March 2023– January 2024**

- Supported management by increasing communication and understanding between crew leads by acting as a direct translator for the tie in the Spanish language.

- Managed and trained 10+ personnel.

- Implemented the use of data collectors to maximize the efficiency of crew routes and track time between stops.

- Improved weekly service efficiency by creating pruning and cutting schedules, increasing efficiency by 10%.

---

## Volunteer Service:

**Missionary for the Church of Jesus Christ of Latter-Day Saints – January 2021 – February 2023**

- Learned and became fluent proficient in speaking and writing in the Spanish language within 3 months.

- Oversaw 15+ missionary companionships and organized special trainings and councils.

- Trained two new missionaries in the Spanish language.

- Practiced budgeting personal finances with the allotted bi-monthly budget given.

**Volunteer Counselor for Amity Elementary School**  
**Varsity Captain for Amity High-School Cross Country Team**

---

## Relevant Skills:

- Certified in the Spanish language through *TrueNorth*: Score 7.2  
- Proficient with Microsoft Office Suite  
- Proficient operating knowledge of the HORIZON banking system
- Proficient in SQL
- Proficient in R
- Proficient in Python



<!-- ### Footer

Last updated: May 2024 -->